# Minepacks Config File

# Language settings
# Language to use, will load the file: /plugins/Minepacks/lang/<your language setting>.yml
Language: en
# How outdated language files should be treated. Overwrite/Update
# Overwrite = old language file will be replaced with new, use this only if you use the language files supplied from the plugin
# Update = the old language file will be updated with the new english messages, all your changes to the file will survive the update
LanguageUpdateMode: Overwrite

# Title to be shown for the opened inventory for everyone except the owner of the backpack. Can contain {OwnerName} (which will be replaced with the players name).
BackpackTitleOther: "&b{OwnerName}'s Backpack"
# The title of the inventory for the owner of the backpack.
BackpackTitle: "&bBackpack"
# Defines how long a player have to wait till he can reopen his backpack.
# Time is in seconds. Values < 1 disable the cooldown.
command_cooldown: -1
# If enabled whe cooldown will be synced between servers. It will also prevent players from leaving and joining to bypass the cooldown.
sync_cooldown: false
# Defines if the content of the backpack get dropped on the death of a player.
# If enabled, it can be disabled for individual players with the "backpack.KeepOnDeath" permission.
drop_on_death: true
# Defines the max amount of columns for a backpack
max_size: 6
# Defines in which game-modes a player can access his backpack (name or id)
allowed_game_modes: [ "SURVIVAL" ]

# Controls for the auto pickup on full inventory function
full_inventory:
  # If items should be collected to the backpack if the players inventory is full
  collect_items: false
  # Interval in seconds how often items around the player should be collected, increase it if it lags the server
  check_interval: 1
  # Radius in which items get collected, in meter/blocks, allow decimals
  collect_radius: 1.5


# Database settings
Database:
  # Database type. MySQL, SQLite or Files
  Type: SQLite
  # Turn off if you want to use player ids created from an other plugin. When using shared tables please check the tables selection
  UpdatePlayer: true
  # Auto database cleanup settings
  AutoCleanup:
    # Defines the max amount of days backpacks will be stored. -1 to disable auto cleanup
    MaxInactiveDays: -1
  # If you would like to use UUIDs, it is recommended not to change this setting unless you know what you are doing!
  # true: Only to use if your server is running in online mode and your minecraft version is 1.7.5 or newer
  # false: In offline mode or for minecraft version below 1.7.5
  # If you are using BungeeCord please set this setting based on your BungeeCord's online mode!!!
  UseUUIDs: true
  # Defines the storage format for UUIDs for compatibility with other plugins (shared tables)
  # true: format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  # false: format: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  UseUUIDSeparators: false
  # Settings only for MySQL
  SQL:
    Host: localhost:3306
    Database: minecraft
    User: minecraft
    Password: minecraft
    #The max amount of connections to the database the connection pool will open
    MaxConnections: 2
  # Tables settings for shared tables when using MySQL - Advanced MySQL Settings
  # Use these settings only if you know what you are doing!!!!
  # Do only change this settings if you know what you are doing and have some basic MySQL knowledge!!!
  # Changing settings down here after you have used this plugin may result in data inconsistency!!!
  Tables:
    # Table names
    # Don't change the players table if you have backpacks stored in your database already! Player id's might wont match anymore resulting data inconsistency.
    User: backpack_players
    Backpack: backpacks
    Cooldown: backpack_cooldowns
    # Field settings for the tables
    # Do not change them after the tables have been generated!
    # If you like to change them after the tables have been generated alter the tables manually or delete them (the system then will regenerate them).
    Fields:
      User:
        Player_ID: player_id
        Name: name
        UUID: uuid
      Backpack:
        Owner_ID: owner
        ItemStacks: itemstacks
        Version: version
        LastUpdate: lastupdate
      Cooldown:
        Player_ID: id
        Time: time
  # Settings controlling the cache behavior of the plugin. You may can optimize it a little bit depending on your player count, ram or cpu bottlenecks.
  Cache:
    UnCache:
      # The strategie used to uncache offline players. Options
      #     interval (offline players get uncached every x seconds)
      #     intervalChecked (like interval, but also ensures that the player is already offline for at least the interval time, add's a cpu overhead)
      #     ondisconnect (player instantly gets uncached as soon as he disconnects, may adds overhead if other plugins try to access the player data when they go offline, also it may be problematic for players with unstable connections)
      #     ondisconnectdelayed (player gets uncached x seconds after he went offline, adds overhead on disconnect, you shouldn't use this with a lot of players joining and leaving.)
      Strategie: interval
      # Used for the interval based uncaching algorithms. Also used as delay for ondisconnectdelayed. Value in seconds. Default: 600 = 10 minutes
      Interval: 600
      Delay: 600

Shulkerboxes:
  # This setting controls whether players can put shulkerboxes into their backpacks.
  PreventInBackpack: true
  # This setting allows to disable shulkerboxes all together. Players won't be able to craft or use them.
  DisableShulkerboxes: false
  # This settings controls how existing shulkerboxes are handled if they are disabled.
  Existing:
    # Every existing shulker-box will be removed when a player tries to interact with it. The content will be lost.
    Remove: false
    # Every existing shulker-box will be destroyed when a player tries to interact with it. The content will be dropped to the ground.
    Destroy: false

ItemFilter:
  # Enables the item filter. Make sure to define items to be filtered.
  Enable: false
  # List off items not allowed in the backpack. Can be name or id.
  Blacklist: []

# Enables/Disables the auto-update function of the plugin.
auto-update: true

# Disables the info that V2 has been released and should be downloaded. You should only use this option if your MC version is not compatible with V2.
DisableV2Info: false

# Config file version. Don't touch it!
Version: 14